FROM ubuntu
LABEL MAINTAINER='Yoann Delattre "github.com/yoanndelattre | twitter.com/yoanndelattre_"'
RUN apt-get update && apt-get upgrade -y && apt-get -y clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
CMD /bin/bash